# Этап 1: Сборка
FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем статически связанный бинарник
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/

# Этап 2: Запуск
FROM alpine:3.19

WORKDIR /app

# Устанавливаем сертификаты для HTTPS запросов
RUN apk --no-cache add ca-certificates

# Копируем бинарник из этапа сборки
COPY --from=builder /app/main .

# Переменные окружения (значения по умолчанию, можно переопределить в docker-compose)
ENV PORT=8081
ENV DB_HOST=postgres
ENV DB_USER=postgres
ENV DB_PASS=postgres
ENV DB_NAME=cinema_db
ENV DB_PORT=5432
ENV DB_SSLMODE=disable
ENV LOG_LEVEL=info

# Открываем порт
EXPOSE 8081

CMD ["./main"]
